# Site settings
title: Nerd-Monster - Local Atlanta Design and Development Studio
email: create@nerdmonster.design
description: Local Atlanta Design and Development Studio
baseurl: '/nerd-monster'
url: "http://nerdmonster.design" # the base hostname & protocol for your site
twitter_username: nd-monster


# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Santiago Gomez
      layout: "post"
      category: weekly-blog
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      author: Santiago Gomez
      layout: "post"
      category: drafts
      
